const locations = [
  {
    name: "University of Oxford",
    locationName: "Oxford, United Kingdom",
    category: "university",
    coordinates: [51.7548, -1.2544],
    shortInfo: "Bachelor of Civil Law (BCL) • 10-Month Program • Highly prestigious postgraduate degree. Tuition: £49,960 (approx. €57,909).",
    requirements: "🎓 DEGREE FORMAT\n• Equivalent to an elite, top-tier international LLM.\n• Module Choice: Take either 4 full modules OR 3 full and 2 half modules.\n\n📊 CRITERIA METRICS\n• GPA Target: Requires a minimum score of 3.7 out of 4.0.\n• English Language: Higher-level IELTS score of 7.5 overall.\n• Sub-sections: Strict minimum of 7.0 required in every individual component.\n• CRITICAL: You must take and pass the IELTS BEFORE applying to Oxford so you can submit verification immediately.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Registration expected to open around September 29, 2026.\n• Strict Deadline: Hard close for law applications occurs strictly at the end of January.\n\n📝 FILE REQUISITES\n• Personal Statement: Explain why Oxford? Why the intersection of energy and law? Focus on your core purpose—do not just list past achievements. (Let's ask Martje about her process!)\n• Legal Writing Piece: Submit 1 undergraduate or professional essay (max. 2,000 words) demonstrating your legal reasoning and style.\n• Academic References: 3 references required. Ensure your professors speak specifically to your academic ranking and research capability.",
    logistics: "✈️ STUDENT VISA\n• Flow: Receive unconditional offer -> Oxford issues a CAS (Confirmation of Acceptance for Study) once all conditions are met.\n• Medical: Mandates a tuberculosis (TB) test certificate from a UKVI-approved clinic in Kathmandu.\n• Financial Proof: Must prove funds covering full tuition + living costs (approx. £1,334/month for up to 9 months).\n• Biometrics: Arranged via appointment at the VFS Centre in Chhaya Center, Thamel.\n\n💰 SCHOLARSHIPS\n• Weidenfeld-Hoffmann Scholarship: Full-ride funding for emerging markets. Tick the box on the main application and upload the specific Leadership Statement form (focuses on your leadership in Nepal & public commitment). *Note: Requires intent to return to Nepal post-graduation. Loophole: Working for an international org like the UN satisfies this condition.*\n• Clarendon Fund: Automatic consideration for all applicants based purely on academic excellence. No return restrictions, full-cost coverage. (The 2,000-word entry essay must be flawless for this!)\n• Rhodes Global Scholarship: Most prestigious globally. Only 2 openings given worldwide per year. Requires official nomination from her university Dean.\n\n🧭 ECOSYSTEM PERKS\n• UNFCCC-UNU Fellowship: Perfect institutional bridge to secure a 1-2 year contract (€2,330/month) at the UN in Bonn right after graduating. Highly prioritizes women from LDCs. Apply in October 2027 while studying.\n• Oxford Sustainable Law Programme: Attend every speech and drinks reception to network directly with visiting UN and EU officials.\n• Extra: Engage with the Oxford Climate Society or compete in Jessup/Price Media Moot Courts."
  },
  {
    name: "London School of Economics (LSE)",
    locationName: "London, United Kingdom",
    category: "university",
    coordinates: [51.5144, -0.1165],
    shortInfo: "Master of Laws (LLM) • 12-Month Program • Situated in Holborn, the heart of London's legal quarter. Tuition: £36,100 (approx. €43,300).",
    requirements: "🎓 DEGREE FORMAT\n• Standard international Master of Laws (LLM) structure running full-time over 1 year.\n• Structure: Take modules totaling 4.0 full units (typically 8 half-unit blocks).\n• Dissertation: Mandatory 10,000-word Legal Research and Writing Skills thesis.\n\n📊 CRITERIA METRICS\n• GPA Target: Strict minimum of 3.5 out of 4.0 (First-Class legal degree equivalent).\n• English Language: IELTS score of 7.5 overall.\n• Sub-sections: Minimum 7.0 in Reading, Writing, Listening; minimum 6.5 in Speaking.\n• FLEXIBILITY BUFFER: Unlike Oxford, LSE allows you to apply before taking the IELTS. If accepted, they issue a conditional offer giving you until July to submit scores.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: System opens up in October 2026 for the 2027 intake.\n• CRITICAL - Rolling Admissions: LSE operates on a first-come, first-served basis. If the program fills up early (e.g., December), it closes. Apply early in October/November!\n\n📝 FILE REQUISITES\n• Statement of Academic Purpose: Heavy academic focus (1,000 to 1,500 words). Clearly state why LSE and detail interest in modules like 'International Law and Climate Change' or 'Transnational Environmental Law'.\n• Documentation: Requires 2 academic references. No written essays or writing samples are required upfront.",
    logistics: "✈️ STUDENT VISA\n• Financial Proof: Higher maintenance tier required because LSE is in central London. Must prove full tuition + £1,529/month for 9 months (Total maintenance: £13,761).\n• Logistics: Requires a TB test certificate from the UKVI clinic in Kathmandu. CAS is issued after an unconditional offer is finalized and a £2,500 deposit is cleared. Biometrics processed at Chhaya Center, Thamel.\n\n💰 SCHOLARSHIPS\n• Graduate Support Scheme (GSS): LSE’s primary need-based pot (£5,000 to £20,000). Fill out the form in the applicant portal right after submitting the main dossier.\n• LSE Master’s & Anniversary Awards: Automatically considered for these larger fund lines if your financial need is extreme (common for LDC applicants) via your GSS data sheet.\n• Chevening Scholarship: Fully funded full-ride path, but carries a strict rule requiring you to return to Nepal for 2 years post-degree.\n• Commonwealth Shared Scholarship: Highly competitive track covering all fees, flights, and living allocations for Nepalese students.\n\n🧭 ECOSYSTEM PERKS\n• Official Specialism: If you select 4 modules within the Environment & Energy track, your final degree certificate will officially specify: 'LLM in Environment and Energy Law'.\n• Location Advantage: Located 15 minutes from the Royal Courts of Justice. Elite energy law firms (e.g., Linklaters, Herbert Smith Freehills) host exclusive recruitment events on campus.\n• Grantham Research Institute: LSE’s world-famous climate change research center. Attend events here to connect with specialized dissertation supervisors."
  },
  {
    name: "University of Cambridge",
    locationName: "Cambridge, United Kingdom",
    category: "university",
    coordinates: [52.2043, 0.1149],
    shortInfo: "Master of Law (LLM) • 9-Month Program • World-renowned legal education within a traditional collegiate framework. Base Tuition: ~£32,214+.",
    requirements: "🎓 DEGREE FORMAT\n• Intensive 9-month taught master's course running from October to the end of June.\n• Structure: Take 4 courses in total.\n• Dissertation Option: Uniquely allows writing a substantial research thesis in place of a final written examination for one course.\n\n📊 CRITERIA METRICS\n• GPA Target: Requires a strict First Class degree in law or its absolute international equivalent (typically 3.7+ out of 4.0).\n• English Language: IELTS score of 7.5 overall.\n• Sub-sections: Strict minimum of 7.0 in all individual sub-sections (Reading, Writing, Listening, Speaking).\n• CRITICAL: Like Oxford, language scores must be present BY the initial application deadline. No conditional language waivers are issued late.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Portal opens in early September. The strict hard close occurs in early December (typically Dec 2).\n• Process - Gathered Field: Cambridge holds all applications and reviews them as a single pool after the deadline. Decisions release around March 1st.\n\n📝 FILE REQUISITES\n• Submission Package: Requires a tailored personal statement explicitly highlighting your \"Reasons for Applying\", your intended modules, and your research background.\n• References: Requires 2 academic references uploaded on official templates.",
    logistics: "✈️ STUDENT VISA\n• Financial Proof: Must prove capability to cover full tuition + standard living costs outside London (approx. £1,305/month for the 9-month duration).\n• Logistics: Requires an approved Kathmandu TB test certificate, a university-issued CAS code, and a biometrics routing at Chhaya Center, Thamel.\n\n💰 SCHOLARSHIPS\n• Gates Cambridge Scholarship: Elite full-cost global scholarship. Requires a separate personal statement essay within the portal detailing your leadership potential and commitment to improving the lives of others.\n• Cambridge Trust: Ensure you check the centralized funding box on your main application form to unlock automatic consideration for a massive array of full and partial university trust lines.\n\n🧭 ECOSYSTEM PERKS\n• Official Specialism: Passing 3 out of your 4 modules within a designated track unlocks an official specialism title on your certificate (e.g., International Law).\n• Collegiate System: Placed inside an individual Cambridge College (e.g., Trinity, Pembroke), providing a built-in, elite, interdisciplinary support and networking circle."
  },
  {
    name: "Leiden University",
    locationName: "Leiden, Netherlands",
    category: "university",
    coordinates: [52.1561, 4.4856],
    shortInfo: "Master of Laws (Regular / Advanced) • 12-Month Program • Renowned European legal hub near The Hague. Tuition: €20,900 to €26,300.",
    requirements: "🎓 DEGREE FORMAT\n• Full 1-year master's program beginning in early September.\n• Focus Paths: Choose between a standard LLM (Public International Law / European Law with sustainability tracks) OR an Advanced LLM (highly specialized, smaller cohort sizes).\n\n📊 CRITERIA METRICS\n• GPA Target: Strong Law Bachelor's equivalent to an upper-second or first-class Dutch tier (typically 3.4+ out of 4.0).\n• English Language: IELTS score of 7.0 overall.\n• Sub-sections: Strict minimum of 6.5 in all individual sub-bands.\n• FLEXIBILITY BUFFER: Allows submitting your application before your final IELTS test is taken. They will issue a conditional offer setting a target date (usually July) to submit scores.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Open in October. The strict hard deadline for non-EU/EEA students requiring a visa is April 1st.\n• Strategic Asset: The later April deadline makes Leiden an excellent structural fallback option if early UK timelines (December/January) feel too compressed.\n\n📝 FILE REQUISITES\n• Packet Requirements: Requires a comprehensive CV in English, complete academic transcripts, 2 academic reference letters, and a well-focused Motivation Letter tracking your interest in global legal architecture.",
    logistics: "✈️ SCHENGEN VISA\n• Smooth Relocation: Leiden's Student Visa Office completely handles and submits your resident visa paperwork (MVV/VVR) directly to the Dutch IND on your behalf once admitted.\n• Financial Proof: Must prove access to full tuition fees + roughly €15,000 for standard annual living allowances set by the state.\n• Logistics: Biometrics are processed directly at the Dutch Embassy in Kathmandu.\n\n💰 SCHOLARSHIPS\n• LExS (Leiden University Excellence Scholarship): Elite line for non-EU talents. Offers three tiers: Platinum (100% tuition coverage), Gold (75% coverage), or Silver (50% coverage). Requires uploading a dedicated competitive motivation essay during initial application.\n• NL Scholarship: A fixed, merit-based entry grant of €5,000 awarded to selective international master's entries.\n\n🧭 ECOSYSTEM PERKS\n• The Hague Pipeline: Located a 15-minute train ride from The Hague—the international capital of peace and justice. Offers immediate local access to the International Court of Justice (ICJ), Permanent Court of Arbitration (PCA), and top climate NGOs.\n• Environment: The Faculty of Law is situated in the historic Kamerlingh Onnes Building, providing an inspiring European academic environment."
  },
  {
    name: "University of Groningen",
    locationName: "Groningen, Netherlands",
    category: "university",
    coordinates: [53.2194, 6.5665],
    shortInfo: "LLM in Energy and Climate Law • 1-Year Program • Situated right inside the center of the Dutch \"Energy Valley\". Tuition: €22,200.",
    requirements: "🎓 DEGREE FORMAT\n• Highly specialized, dedicated 1-year master's program launching September 1st.\n• Focus: Investigates core legal mechanisms of energy market liberalization, clean-tech regulation (hydrogen/renewables), and how EU climate law dictates global frameworks.\n\n📊 CRITERIA METRICS\n• GPA Target: Requires a solid academic record equivalent to at least a 7.0/10 on the formal Dutch grading scale.\n• English Language: IELTS academic score of 7.0 overall.\n• Sub-sections: Minimum of 6.5 required in all individual sub-bands.\n• BUFFER: Conditional entry applications are fully accepted before graduation or language testing is complete.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Open in October. The absolute final close for non-EU students needing immigration processing is May 1st.\n\n📝 FILE REQUISITES\n• Motivation Statement: Strict maximum threshold of 650 words. Must be entirely original work—the board explicitly states that utilizing AI generation tools for this letter is forbidden.\n• Documents: Comprehensive CV in English and exactly 1 academic reference letter from a university lecturer written on formal letterhead.",
    logistics: "✈️ SCHENGEN VISA\n• Coordination: The central university visa desk completely manages your visa processing (MVV/VVR) directly with the Dutch immigration authorities (IND) following your acceptance.\n• Financial Proof: Must prove financial capability covering the baseline tuition fee + roughly €15,000 for standard annual living allocations.\n• Logistics: Biometrics are handled via direct appointment at the Dutch Embassy in Kathmandu.\n\n💰 SCHOLARSHIPS\n• Eric Bleumink Fund: Highly prestigious full-ride scholarship covering 100% of tuition, travel, living costs, and health insurance. Targeted specifically at top-tier talents from developing nations. (Extremely competitive).\n• Groningen Talent Grant: Partial funding awards specifically designated for elite international masters applicants.\n• NL Scholarship: A €5,000 partial entry grant awarded based on purely academic merit during the application cycle.\n\n🧭 ECOSYSTEM PERKS\n• Energy Valley Hub: Groningen sits at the heart of a European-recognized Hydrogen Valley. This unique location allows the university to bring top-tier green energy corporate executives and policymakers directly into classes.\n• Dual-Degree Option: Features an optional elite partnership framework with George Washington University (GW Law) in Washington D.C. for dual insights into both EU and US climate/environmental legal codes."
  },
  {
    name: "KU Leuven",
    locationName: "Leuven, Belgium",
    category: "university",
    coordinates: [50.8798, 4.7005],
    shortInfo: "Master of Laws (LLM) • 1-Year Advanced Master • Ranked #1 in the EU for Law (THE). Tuition: €9,493.90.",
    requirements: "🎓 DEGREE FORMAT\n• Intensive 1-year Advanced Master's program (60 ECTS) running mid-September to June.\n• Specialized Track: International and European Business Law path matches top corporate and institutional criteria.\n\n📊 CRITERIA METRICS\n• Background: Requires a competitive academic Bachelor's or Master's degree in Law.\n• English Language: IELTS Academic score of 7.0 overall.\n• Sub-sections: Remains highly competitive as long as you have no more than two 6.5 scores or one 6.0 score on sub-sections.\n• BUFFER: Draft application files are fully accepted before transcripts or language proofs are finalized. Review is rolling; final documents are due by July 1st.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Open in October. The absolute final deadline for non-EEA citizens requiring a student visa is June 1st.\n• Process - Rolling Admissions: Evaluated continuously with responses generated in 6-8 weeks. Applying early (October to March) is strongly urged before slots close.\n\n📝 FILE REQUISITES\n• Packet Requirements: English CV, passport scan, formal transcripts, and a targeted 1-page Motivation Letter in English specifying which courses and professors attract you.",
    logistics: "✈️ SCHENGEN VISA\n• Financial Proof: Must provide certified proof of sufficient financial capability covering tuition fees and monthly international student living allowances.\n• Logistics: Visa processing is completed through designated VFS application center pipelines serving applicants from Kathmandu.\n\n💰 SCHOLARSHIPS\n• Germaine Cox Scholarship: Specialized, one-time partial tuition fee waiver awarded to excellent LLM students experiencing verified financial need.\n• Master Mind Scholarship: Awarded by the Government of Flanders for outstanding international talents. Highly competitive across all university faculties. Strict application deadline is January 15th.\n\n🧭 ECOSYSTEM PERKS\n• The Brussels Pipeline: Located just 20 minutes away from Brussels—the political capital of the European Union.\n• High Placement Rate: Around 20% of all LLM alumni instantly secure careers inside Brussels institutions (EU organs, global law firms, regulatory entities), and another 20% land elite roles within the wider Benelux market."
  },
  {
    name: "Bucerius Law School",
    locationName: "Hamburg, Germany",
    category: "university",
    coordinates: [53.5606, 9.9822],
    shortInfo: "Master of Law and Business (LLM / MLB) • 12-Month Program • Germany's leading private law school. Tuition: €25,000.",
    requirements: "🎓 DEGREE FORMAT\n• Full 12-month interdisciplinary program starting in Fall (Autumn trimester).\n• Structure: Combines international business law with corporate management principles.\n• Experience: Curriculum features an integrated mandatory 8-week corporate internship.\n\n📊 CRITERIA METRICS\n• Academic background: Completed undergraduate or graduate degree in Law, Business, or Economics.\n• Work Experience: Requires at least one year of relevant professional experience gained post-graduation.\n• English Language: Minimum IELTS score of 7.0 overall (or TOEFL iBT score of 100).",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Opens in autumn. Features a hard priority deadline for funding/visas around January 15th.\n• Strategic Benefit: Submitting by January 15th applies an automatic €2,000 Early Bird Discount. General final entries close mid-May.\n\n📝 FILE REQUISITES\n• Packet Requirements: Academic transcripts (with class ranking description), standard resume/CV, motivation statements, and 2 letters of recommendation.",
    logistics: "✈️ NATIONAL VISA\n• Entry Deposit: Requires a €1,000 non-refundable deposit within 2 weeks of acceptance to secure your seat (deducted from total tuition).\n• Financial Proof: Must prove capability to cover German government-mandated living expenses via a blocked account (Sperrkonto, roughly €11,900 total allocation).\n• Logistics: Standard biometrics appointment scheduled at the German Embassy in Kathmandu.\n\n💰 SCHOLARSHIPS\n• Bucerius Global & Business Excellence Scholarships: Elite full-tuition merit awards specifically designed for exceptional young professionals from emerging markets. Must apply fully by January 15th.\n• Deutschlandstipendium: Provides a stipend of €300/month based on top academic marks and voluntary social commitment (apply by June 15th once admitted).\n• Aid Waivers: Merit and need-based partial grants allocated by submitting the hauseigenen financial aid form.\n\n🧭 ECOSYSTEM PERKS\n• Mandatory Internship: The 8-week module places international students inside elite German corporations, multinational institutions, or major international law offices.\n• German Tax Benefit: If she stays to work in Germany post-graduation, MLB tuition fees are fully tax-deductible as anticipated professional expenses (Werbungskosten).\n• Environment: Beautiful private campus right next to the historic 'Planten un Blomen' park in central Hamburg."
  },
  {
    name: "Stockholm University",
    locationName: "Stockholm, Sweden",
    category: "university",
    coordinates: [59.3654, 18.0583],
    shortInfo: "LLM in Environmental Law • 1-Year Intensive Program (60 credits) • Focuses on transboundary climate, energy, and ecosystem regulation. Tuition: 90,000 SEK (approx. €7,900).",
    requirements: "🎓 DEGREE FORMAT\n• Highly integrated 1-year taught program running from late August to June (60 credits).\n• Core Focus: Focuses deeply on transboundary environmental law, global climate policy, and social-ecological resilience frameworks.\n\n📊 CRITERIA METRICS\n• Background: Recognized undergraduate degree in Law of at least 180 ECTS credits. Prior environmental law coursework is preferred.\n• English Language: Proficiency equivalent to Swedish English 6 course. Requires a minimum overall IELTS score of 6.5, with no sub-section lower than 5.5.\n• NOTE: Her 7.5 IELTS easily exceeds this, making her language eligibility absolute.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Single unified international application round opens in mid-October and closes strictly on January 15th.\n• Central Portal: Handled completely online via the centralized Swedish portal 'University Admissions' (universityadmissions.se).\n\n📝 FILE REQUISITES\n• Packet Requirements: Requires a dedicated Stockholm template Personal Statement, an academic CV (max. 2 pages), and 2 signed letters of recommendation on official letterheads.",
    logistics: "✈️ RESIDENT PERMIT\n• Process: Handled by the Swedish Migration Agency (Migrationsverket). Once the first tuition installment (45,000 SEK) is processed, she can apply for the resident permit for studies.\n• Financial Proof: Government-mandated minimum living allowance proof (approx. 10,656 SEK per month of study).\n• Logistics: Biometrics and passport verification are arranged via appointment serving Nepal.\n\n💰 SCHOLARSHIPS\n• Swedish Institute (SI) Scholarship for Global Professionals: MAJOR ADVANTAGE! Nepal is on the priority list. It provides 100% full tuition coverage, a monthly living allowance of roughly 11,000 to 12,000 SEK, and a comprehensive travel grant. Requires at least 3,000 hours of documented work/leadership experience.\n• Stockholm University Scholarship Scheme: Merit-based tuition waivers offered directly by the university to elite non-EU master's applicants.\n\n🧭 ECOSYSTEM PERKS\n• Treaty Alignment: The program places immense emphasis on transboundary ecosystem governance, making graduates highly attractive for international environmental policy hubs and climate risk assessment groups."
  },
  {
    name: "UNFCCC Secretariat (UN Campus)",
    locationName: "Bonn, Germany",
    category: "career",
    coordinates: [50.7180, 7.1235],
    shortInfo: "Legal Affairs Division • The nerve center of global climate change law. Core hub for managing the Paris Agreement compliance.",
    requirements: "💼 TARGET DESK\n• Legal Affairs Division: Provides crucial advice on international treaty frameworks, compliance mechanisms under the Paris Agreement, and intergovernmental negotiating processes.\n\n📊 CORE COMPETENCIES\n• Languages: Fließendes Englisch is a mandatory prerequisite. A strong command of another official UN language (especially French or Spanish) is an immense competitive asset.\n• Skills: Exceptional legal analysis, drafting intergovernmental treaty commentaries, and absolute cultural sensitivity.",
    process: "🧭 ENTRY PIPELINES\n\n1️⃣ Golden Ticket: UNFCCC-UNU Early Career Climate Fellowship\n• Profile: A highly elite 1-2 year fellowship tailored specifically for young professionals from developing countries (especially LDCs).\n• Priority: Women from LDCs have the highest recruitment priority. It places fellows directly into specialized desks like Legal Affairs.\n• Timeline: Typically opens around January-March (while studying her Master's) or right after graduation. Stipend: ~€2,330/month tax-free. Apply in October 2027.\n\n2️⃣ The \"Foot in the Door\": UN Secretariat Internship\n• Process: 2-6 month legal internships within the secretariat. While traditionally unpaid, doing an internship *while living in Germany* (e.g., studying at Bucerius, Groningen, or Leuven) drastically minimizes logistical friction. Apply via Inspira.\n\n3️⃣ Professional Track: P-2 Associate Legal Officer\n• Criteria: Requires an advanced university degree (Master's / LLM) in international law or environmental law, plus a minimum of 2 years of relevant professional experience (specialized research assistant work counts).",
    logistics: "🇩🇪 LOCAL ADVANTAGE\n• Post-Study Visa Support: If she completes an LLM within the EU or Germany, securing residency and work authorization in Germany becomes drastically simpler compared to arriving cold from Nepal.\n• The Bonn Ecosystem: The UN Campus sits right next to other crucial climate powerhouses, including the IDOS (German Institute of Development and Sustainability) and ICLEI World Secretariat, offering a massive localized network for informational interviews and networking."
  },
  {
    name: "Geneva Graduate Institute (IHEID)",
    locationName: "Geneva, Switzerland",
    category: "university",
    coordinates: [46.2223, 6.1458],
    shortInfo: "LLM in International Law • 10-Month Intensive Program • Featuring a highly specialized track in International Environmental Law and Governance. Tuition: CHF 25,000.",
    requirements: "🎓 DEGREE FORMAT\n• Elite, intensive 10-month master's running from September to June.\n• SPECIALIZED TRACK: Features a core focus path in 'International Environmental Law and Governance'. Includes elite modules like International Climate Change Law and Compliance Mechanisms under Environmental Treaties.\n\n📊 CRITERIA METRICS\n• Academic background: Must possess a complete legal education that entitles you to sit for the bar exam in your country of origin (e.g., an LL.B. degree).\n• English Language: Minimum IELTS Academic score of 7.0 overall, with a strict minimum of 6.5 in each individual sub-section.\n• Selection Focus: Academic transcripts and extracurricular legal engagements (Moot courts or specialized paper publications) carry high selection weights.",
    process: "⏳ CHRONO TIMELINE\n• Application Window: Open in October.\n• CRITICAL SCHOLARSHIP DEADLINE: January 15th is the absolute hard deadline if you want to request Financial Aid. No exceptions are made for funding after this date.\n• General Round: A final admission portal window remains open until March 1st, but no financial support lines are unlocked in this period.\n\n📝 FILE REQUISITES\n• Packet Requirements: Online dossier submission requiring a personal motivation letter (max. 800 words), an academic CV, transcripts with grade scales, and 2-3 formal academic reference letters on letterheads.",
    logistics: "✈️ SWISS VISA\n• Flow: Once admitted, the student visa application is completed via designated appointment pipelines serving Nepal.\n• Financial Proof: Swiss migration authorities strictly require proof of financial capability covering at least CHF 2,000 per month of study (approx. CHF 20,000 total maintenance allocation) in addition to tuition coverage.\n\n💰 SCHOLARSHIPS\n• Full Financial Aid Packages: Highly competitive full scholarships are available. These cover the complete cost of tuition (CHF 25,000) plus a full maintenance stipend towards Geneva living costs (CHF 18,000) for a total package value of CHF 43,000. *Must submit by Jan 15.*\n\n🧭 ECOSYSTEM PERKS\n• Global Capital Advantage: Geneva is the primary international seat for the UN European Headquarters, the World Trade Organization (WTO), and the UN Environment Programme (UNEP), placing her directly adjacent to top climate governance entities.\n• Applied Training: Enhances core advocacy and policy skills through hands-on Law Clinics, exclusive practitioner roundtables, and an 8,000-word master's paper geared directly for peer-reviewed journal publications."
  },
  {
    name: "Asian Development Bank (ADB)",
    locationName: "Manila, Philippines",
    category: "career",
    coordinates: [14.5566, 121.0632],
    shortInfo: "Office of the General Counsel • Manila Headquarters • Premier climate and infrastructure bank for the Asia-Pacific region. Fully tax-free international official benefits.",
    requirements: "💼 TARGET DESK\n• Office of the General Counsel (OGC): Advises on sovereign and non-sovereign infrastructure finance, guarantees ESG compliance across all investments, and drafts sustainable transition policies.\n• Climate Finance Desk: Specializes in blending multilateral public funds with private capital for green energy transformations.\n\n📊 CORE COMPETENCIES\n• Age Limit: Must be strictly under 32 years old at the time of entering the Young Professionals Program (YPP).\n• Education Tier: Requires an advanced university degree in law (an LLM from an elite institution perfectly satisfies this).\n• Background Focus: Demonstrated academic or practical specialization in ESG safeguards, renewable energy regulation, or international environmental law.",
    process: "🧭 ENTRY PIPELINES\n\n1️⃣ The Golden Gate: Young Professionals Program (YPP)\n• Profile: The absolute premier, highly structured fast-track program designed for elite young talents under 32.\n• Rotation Cycle: Consists of a 3-year foundational framework involving mandatory cross-departmental micro-rotations (e.g., from Legal into Sovereign Infrastructure Loans).\n• Application Window: Typically opens annually around May to July. Highly realistic for her immediately after completing her LLM.\n\n2️⃣ Direct Entry: Associate Legal Officer (International Staff)\n• Pathway: Standard competitive hiring track via the ADB Career Portal. Requires 2-3 years of specialized post-degree legal or academic research experience (university assistant positions are fully counted).\n\n3️⃣ Institutional Pivot: Legal Internship Program\n• Strategy: A 4-12 week assignment inside the OGC in Manila during her LLM winter/summer break. Excellent way to secure a champion for the final YPP selection panel.",
    logistics: "✈️ EXPAT RELOCATION\n• Official Visa Status: Issued an official international diplomat-grade visa by the Philippine government, ensuring frictionless relocation from Kathmandu.\n• Moving Allocation: Comprehensive relocation grant covering 100% of flights, shipping costs, and initial luxury temporary housing in Manila.\n\n💰 TAX-FREE COMPENSATIONS\n• Net Advantage: International Staff salaries are entirely tax-free (exempt from income taxes), resulting in a massive financial advantage compared to corporate tax brackets.\n• Allowances: Includes substantial institutional allowances for housing rental, premium worldwide private health insurance, and international retirement pension assets.\n\n🧭 ECOSYSTEM PERKS\n• Regional Sovereign Advantage: Nepal is a founding member country, unlocking special regional diversity quotas that heavily favor elite applicants from South Asia over over-represented nations.\n• Strategic Impact: Direct legal oversight over multi-billion dollar green energy transitions across developing Asia, serving as the ultimate credential for future executive roles at the UN or World Bank."
  }
];
